### ISSUE TITLE
Support Local Storage

### ISSUE THREAD

**Issue by lidel** [darobin/proto-handler-reqs#1]
This is worth discussing:

> 3.7 Local Storage
> 
> Does the scheme support setting cookies, using local storage, etc. and if so according to which rules.
> 
> Proposal. Extension-supported schemes do not support any of these mechanisms so as to avoid impacting privacy. However, the extension can expose a form of storage if desired.

It effectively breaks ability to load HTML apps via `foo://`, making it impossible to use `ipfs://` in ipfs-companion beyond basic static pages.  

Without Local Storage tied to content root UX becomes pretty bad: users of subdomain gateways  (which are how ipfs:// works in Brave)  have  local storage tied to the `ipfs://cid` Origin. 

Perhaps we could change this section to reflect what happens on subdomain gateways and in brave? (Local Storage, cookies, and APIs scoped to the Origin of  authority: `foo://authority` (in IPFS the root CID is the opaque authority)

**Comment by lidel** [comment]
@darobin @autonome iiuc webextension or PWA can still track user by storing identifiers outside the  protocol handler, so unsure what is the privacy impact.

Would it be ok to change this section and say Local Storage, Cookies, APIs etc are scoped to the Origin based on the authority component passed in the URI?   It feels like something that would be compatible with existing web security model, and would not break dapps.

**Comment by darobin** [comment]
The reason I went strict with this was because I was unsure how this would work with partitioned caching given that partitions aren't (last I checked) fully specified and interoperable across browsers. But if this doesn't support cache partitioning, it basically provides a path to reset some of the most important parts of the past five years of progress in browser privacy.

That said, I _think_ (but need to check) that all the existing partitioning work is origin-keyed, which we could make work. This would make injected content no worse than the current situation.
